# Generated by Django 3.2.4 on 2021-06-20 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riddles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='option',
            old_name='riddles',
            new_name='riddle',
        ),
    ]
